
slides:
    overview:
        overview: true
        data:
            x: 0
            z: 1500
    home:
        view: true
    details:
        view: true
        data:
            x: 2500
            z: -1000
            "rotate-y": 90
    experiences:
        view: true
        data:
            x: 0
            z: -2000
            "rotate-y": 180

config:
    inactive_opacity: 1
    data:
        transition-duration: 1000
        min-scale: 1
    attr:
        style: "width: 100%;height: 100%;"
